In [7]:
!pip install torch


In [8]:
import torch
print(torch.__version__)

2.12.0+cpu


In [9]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a Tensor

In [10]:
# using empty
a = torch.empty(2,3)

In [11]:
# check type
type(a)

torch.Tensor

In [12]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# using rand
torch.rand(6,3)

tensor([[0.7299, 0.6512, 0.6645],
        [0.0767, 0.4351, 0.3494],
        [0.4905, 0.3876, 0.2652],
        [0.5675, 0.9169, 0.6055],
        [0.3831, 0.4555, 0.1281],
        [0.4563, 0.0196, 0.0937]])

In [15]:
# manual_seed
torch.manual_seed(500)
torch.rand(2,3)

tensor([[0.5820, 0.1338, 0.7995],
        [0.3071, 0.6526, 0.6105]])

In [16]:
torch.manual_seed(500)
torch.rand(4,5)

tensor([[0.5820, 0.1338, 0.7995, 0.3071, 0.6526],
        [0.6105, 0.1575, 0.6983, 0.7883, 0.7981],
        [0.4593, 0.8997, 0.2518, 0.5648, 0.0302],
        [0.5930, 0.6386, 0.4795, 0.6030, 0.7351]])

In [17]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,7))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [19]:
  x = torch.tensor([[7,2,3],[4,5,6]])
  x

tensor([[7, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7602, 0.8872, 0.8153],
        [0.2794, 0.0168, 0.6273]])

## Tensor Data Types

In [25]:
# find data type formate : "name of tensor.dtype"
x.dtype

torch.int64

In [26]:
# assign data type (changes the data type from one to another or can say forces)
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [28]:
# using to()
x.to(torch.float32)

tensor([[7., 2., 3.],
        [4., 5., 6.]])

## Mathematical operations

### 1. Scalar operation

In [29]:
x = torch.rand(2,2)
x

tensor([[0.6037, 0.1817],
        [0.3849, 0.8164]])

In [30]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.3644, 0.0330],
        [0.1482, 0.6665]])

### 2. Element wise operation

In [31]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3086, 0.4626, 0.7494],
        [0.9410, 0.0619, 0.6229]])
tensor([[0.8790, 0.6113, 0.6402],
        [0.0360, 0.4153, 0.2534]])


In [32]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.3086, 0.4626, 0.1091],
        [0.0048, 0.0619, 0.1161]])

In [33]:
c = torch.tensor([1, -2, 3, -4])

In [34]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [35]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [36]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [37]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [38]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [39]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [40]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [41]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[2., 1., 9.],
        [1., 9., 2.]])

In [42]:
torch.sum(e, dim=0)

tensor([ 3., 10., 11.])

In [43]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim=0)

# sum along rows
torch.sum(e, dim=1)

tensor([12., 12.])

In [44]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([1.5000, 5.0000, 5.5000])

In [45]:
# median
torch.median(e)

tensor(2.)

In [46]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [47]:
# product
torch.prod(e)

tensor(324.)

In [48]:
# standard deviation
torch.std(e)

tensor(3.8987)

In [49]:
# variance
torch.var(e)

tensor(15.2000)

In [50]:
# argmax
torch.argmax(e)

tensor(2)

In [51]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [52]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[4, 1, 7],
        [7, 9, 9]])
tensor([[7, 9],
        [2, 5],
        [3, 4]])


In [53]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 51,  69],
        [ 94, 144]])

In [54]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [55]:
# transpose
torch.transpose(f, 0, 1)

tensor([[4, 7],
        [1, 9],
        [7, 9]])

In [56]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[1., 9., 6.],
        [2., 8., 7.],
        [1., 2., 8.]])

In [57]:
# determinant
torch.det(h)

tensor(-55.0000)

In [58]:
# inverse
torch.inverse(h)

tensor([[-0.9091,  1.0909, -0.2727],
        [ 0.1636, -0.0364, -0.0909],
        [ 0.0727, -0.1273,  0.1818]])

### 5. Comparison operations

In [59]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[2, 3, 0],
        [8, 0, 4]])
tensor([[2, 2, 7],
        [9, 7, 0]])


In [60]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[False,  True,  True],
        [ True,  True,  True]])

### 6. Special functions

In [61]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[1., 4., 3.],
        [4., 6., 1.]])

In [62]:
# log
torch.log(k)

tensor([[0.0000, 1.3863, 1.0986],
        [1.3863, 1.7918, 0.0000]])

In [63]:
# exp
torch.exp(k)

tensor([[  2.7183,  54.5981,  20.0855],
        [ 54.5981, 403.4288,   2.7183]])

In [64]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 2.0000, 1.7321],
        [2.0000, 2.4495, 1.0000]])

In [65]:
# sigmoid scaling bw 0 and 1
torch.sigmoid(k)

tensor([[0.7311, 0.9820, 0.9526],
        [0.9820, 0.9975, 0.7311]])

In [66]:
# softmax scaling bw 0 and 1 with sum of all elements as 1
torch.softmax(k, dim=0)

tensor([[0.0474, 0.1192, 0.8808],
        [0.9526, 0.8808, 0.1192]])

In [67]:
# relu
torch.relu(k)

tensor([[1., 4., 3.],
        [4., 6., 1.]])

## Inplace Operations

In [68]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9695, 0.5142, 0.5998],
        [0.1723, 0.0430, 0.7949]])
tensor([[0.8493, 0.7954, 0.2022],
        [0.9894, 0.2137, 0.8185]])


In [69]:
m.add_(n)

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

In [70]:
m

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

In [71]:
n

tensor([[0.8493, 0.7954, 0.2022],
        [0.9894, 0.2137, 0.8185]])

In [72]:
torch.relu(m)

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

In [73]:
m.relu_()

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

In [74]:
m

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

## Copying a Tensor

In [75]:
a = torch.rand(2,3)
a

tensor([[0.5125, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [76]:
b = a

In [77]:
b

tensor([[0.5125, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [78]:
a[0][0] = 0

In [79]:
a

tensor([[0.0000, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [80]:
b

tensor([[0.0000, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [81]:
id(a)

1985799635824

In [82]:
id(b)

1985799635824

In [83]:
b = a.clone()

In [84]:
a

tensor([[0.0000, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [85]:
b

tensor([[0.0000, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [86]:
a[0][0] = 10

In [87]:
a

tensor([[10.0000,  0.6978,  0.4469],
        [ 0.7157,  0.8856,  0.0561]])

In [88]:
b

tensor([[0.0000, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [89]:
id(a)

1985799635824

In [90]:
id(b)

1985799431952

In [91]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [92]:
a.shape

torch.Size([3, 3])

In [93]:
b = torch.empty_like(a)
b


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])